models/notification.py
from sqlalchemy import Column, Integer, String, Boolean
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()
from extensions import db


class Notification(db.Model):
    __tablename__ = "notification"
    id = Column(Integer, primary_key=True, autoincrement=True)
    message = Column(String(1024))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    is_read = db.Column(db.Boolean, default=False)
    product_id = db.Column(db.Integer, db.ForeignKey('product.id'))

controllers/notification.py
from flask import Blueprint, flash, request, render_template, session, redirect, url_for
from models import *
notification_bp = Blueprint(
    'notifications', __name__, url_prefix='/notifications')


def notifications():
    email = session['email']
    user = User.query.filter_by(email=email).first()
    notifications = Notification.query.filter_by(user_id=user.id).all()
    return render_template("website/notifications.html", notifications=notifications)


def mark_read():
    notification_id = request.args.get("notification_id")

    Notification.query.filter_by(id=notification_id).delete()
    db.session.commit()
    return redirect(url_for('notifications.notification'))


notification_bp.add_url_rule('/mark_read', 'mark_read', mark_read , methods=['GET', 'POST'])


notification_bp.add_url_rule('/', 'notification', notifications, methods=['GET', 'POST'])

controllers/user.py
from flask import Blueprint, flash, request, render_template, session, redirect, url_for
from extensions import db
import random
from . import pricescrap
from models import *
user_bp = Blueprint(
    'user', __name__, url_prefix='')


def login():
    try:
        if request.method == 'POST':
            credentials = request.form
            email = credentials['user']
            password = credentials['password']
            if email == "" or password == "":
                flash("!All fields are required")
                return render_template("website/login.html")
            else:
                user = User.query.filter_by(email=email).first()
                if user.email == email and user.password == password:
                    session['email'] = email
                    return redirect(url_for('views.home', email=email))

        elif request.method == 'GET':
            return render_template("website/login.html")
    except Exception as e:
        print("Error while logging in.", e)
    return render_template("website/login.html", error="Invalid Credentials. Please try again.")

def signup():
    try:
        if request.method == 'POST':
            details = request.form
            name = details['name']
            email = details['user']
            password = details['pas']
            cpas = details['cpas']
            mobile = details['mob']
            if name == "" or email == "" or password == "" or cpas == "" or mobile == "" :
                flash("!All fields are required")
                return render_template("website/signup.html")
            else:
                if password != cpas:
                    flash("!Password did not match")
                    return render_template("website/signup.html")
                else:
                    user = User()
                    user.name = name
                    user.email = email
                    user.password = password
                    user.mobile = mobile
                    db.session.add(user)
                    db.session.commit()
                    # cur = mysql.connection.cursor()
                    # rs =cur.execute('insert into user(name,email,password,mobile) values("%s","%s","%s","%s");'%(n,u,p,m))
                    # mysql.connection.commit()
                    return redirect(url_for('user.login'))
        if request.method == 'GET':
            return render_template("website/signup.html")
    except Exception as e:
        print("error", e)
        flash("!Something went wrong , Try Again...")
        return render_template("website/signup.html")


def forgetpass():
    try:
        if request.method == 'POST':
            email = request.form['foremail']
            code = random.randint(111111, 999999)
            pricescrap.forgetpassmail(email, code)
            session['email'] = email
            session['code'] = str(code)
            return render_template("website/newpass.html")
        elif request.method == 'GET':
            return render_template("website/forgetpass.html")
    except :
        flash("!Something went wrong , Try Again...")
        return render_template("website/forgetpass.html")


def profile():

    email = session.get('email')
    try:
        if request.method == 'GET':
            user = User.query.filter_by(email=email).first()

            name, mobile, email = user.name, user.mobile, user.email

            return render_template("website/profile.html", user=name,  mob=mobile , email=email)
        elif request.method == 'POST':
            details = request.form
            n = details['name']
            u = details['user']
            m = details['mob']
            user = User.query.filter_by(email=email).first()
            user.name = n
            user.mobile = m
            user.email = u
            db.session.add(user)
            db.session.commit()
            return render_template("website/profile.html", user=n, email=u, mob=m)
    except :
        flash("!Something went wrong , Try Again...")
        return render_template("website/profile.html", user=name, email=email, mob=mobile)


def newpass():
    try:
        email = session['email']
        code = session['code']
        if request.method == 'POST':
            code1 = request.form['code']
            newp = request.form['pas']
            rnewp = request.form['cpas']
            if code == code1 and newp == rnewp:
                user = User.query.filter_by(email=email).first()
                user.password = newp
                db.session.add(user)
                db.session.commit()
                return redirect(url_for('user.login'))
            else:
                flash("!Something went wrong , Try Again...")
                return render_template("website/newpass.html")
        elif request.method == 'GET':
            return render_template("website/newpass.html")
    except :
        flash("!Something went wrong , Try Again...")
        return redirect(url_for('forgetpass'))




user_bp.add_url_rule('/', 'login', login, methods=['GET', 'POST'])
user_bp.add_url_rule('/signup', 'signup', signup, methods=['GET', 'POST'])
user_bp.add_url_rule('/forgetpass', 'forgetpass', forgetpass, methods=['GET', 'POST'])
user_bp.add_url_rule('/profile', 'profile', profile, methods=['GET', 'POST'])
user_bp.add_url_rule('/profile/newpass', 'newpass', newpass, methods=['GET', 'POST'])

templates/website/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>about</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='website/index.css') }}">
</head>
<body>


    s<header>
      <div class="hea">
        <div class="logo">
<h1><span>P</span>RICE   <span style="padding-left:10px;">T</span>AG</h1>        </div>

        <div class="menu">
         <a href="#" style="display:none;">About Us</a>
          <a href="#" style="display:none;">Sites</a>
          <a href="{{ url_for('profile')}}">Profile</a>
          <a href="#">Dashboard</a>
          <a href="{{ url_for('home')}}" class="hom">Home</a>
        </div>
      </div>
    </header>


</body>
</html>

templates/website/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>dashboard</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='website/index.css') }}">
</head>
<body>
       <header>
      <div class="hea">
        <div class="logo">
<h1><span>P</span>RICE   <span style="padding-left:10px;">T</span>AG</h1>        </div>

        <div class="menu">
          <a href="#" style="display:none;">About Us</a>
          <a href="#" style="display:none;">Sites</a>
            <a href="{{ url_for('user.login') }}" >Log Out</a>
          <a href="{{ url_for('user.profile')}}">Profile</a>
          <a href="{{ url_for('views.dashboard') }}" class="dash">Dashboard</a>
          <a href="{{ url_for('views.home') }}" >Home</a>
            <a href="{{ url_for('notifications.notification')}}">Notifications</a>

        </div>
      </div>
    </header>

<table>
    <tr>    
    <th>Website</th>
    <th>Product Image</th>
    <th>Product Title</th>
    <th>Product Initial Price</th>
    <th>Desired Price</th>
    <th>Product Price Right Now</th>
    <th>url</th>
    </tr>
              {% if products %}
                {% for product in products%}
                    <tr>  
                        <td>{{ product["site"] }}.com</a></td>
                        <td><img src="{{product['img']}}" style="height:110px;width:110px;"></td>
                        <td>{{product["title"]}}</td>
                        <td>{{product["initial_price"]}}</td>
                        <td>{{product["desired_price"]}}</td>
                        <td>{{product["new_price"]}}</td>
                        <td><a href="{{ product['url'] }}" target="_blank" style="font-size:15px;">Click here to go to the Product Page.</a></td>
                        <td><a href="{{ url_for('product.stop_tracking', product_id=product['id']) }}">Stop Tracking</a></td>
                    </tr>
                {% endfor %}
              {% else %}
                    <tr><td colspan="7">No products found.</td></tr>
              {% endif %}
</table>


</body>
</html>

templates/website/forgetpass.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='website/index.css') }}">
  </head>
  <body>
      <div class="hea">
        <div class="logo">
<h1><span>P</span>RICE   <span style="padding-left:10px;">T</span>AG</h1>
        </div>
        <div class="menu">
          <a href="#" style="display:none;">About Us</a>
          <a href="#" style="display:none;">Sites</a>
        </div>
      </div>

      <form class="fpass" action="" method="post">
        <span style="text-decoration:underline;">Username:</span><br><br><input type="text" name="foremail" placeholder="email address:">
        <br><br><button type="submit" name="button" >Get Email</button>
      </form>
  </body>
</html>

templates/website/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='website/index.css') }}">
  </head>
  <body class="loginbody">
      <div class="hea">
        <div class="logo">
          <h1><span>P</span>RICE   <span style="padding-left:10px;">T</span>AG</h1>
        </div>

        <div class="menu">
          <a href="#" style="display:none;">About Us</a>
          <a href="#" style="display:none;">Sites</a>
        </div>
      </div>


      <form class="user" style=".user button:hover{color: black;font-weight: bold;}" method="post">
          {% if error %}
      <span>{{ error }}</span>
      {% endif %}

        <span>Username:</span> <br><input type="text" name="user" placeholder="Enter email id:"><br><br>
        <span>Password:</span> <br><input type="password" name="password" placeholder="Enter password:"><br><br>
        <button type="submit" name="login">LOG IN</button><br><br><br>
        <a href="{{ url_for('user.signup')}}">Create new account?</a><a href="{{ url_for('user.forgetpass') }}" style="padding-left:15px;">Forgot Password?</a>
      </form>
  </body>
</html>

templates/website/newindex.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <title>Home</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static',filename='website/index.css') }}"
    />

    <link
      href="https://fonts.googleapis.com/css?family=Tomorrow&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300&display=swap"
      rel="stylesheet"
    />
  </head>
  <body class="home">
    <header>
      <div class="hea">
        <div class="logo">
          <h1>
            <span>P</span>RICE <span style="padding-left: 10px">T</span>AG
          </h1>
        </div>

        <div class="menu">
          <a href="#" style="display: none">About Us</a>
          <a href="#" style="display: none">Sites</a>
          <a href="{{ url_for('user.login') }}">Log Out</a>
          <a href="{{ url_for('user.profile')}}">Profile</a>
          <a href="{{ url_for('views.dashboard', token=token) }}">Dashboard</a>
          <a href="{{ url_for('views.home')}}" class="hom">Home</a>
                    <a href="{{ url_for('notifications.notification')}}">Notifications</a>

        </div>
      </div>
    </header>
    <!-- welcome,{{email}} -->

    <form method="post">
      <h2>Search Products</h2>
      <br />
      <div class="serdiv">
        <input
          class="search"
          type="text"
          name="search"
          placeholder="Paste The Product URL  And Press Enter"
          autocomplete="off"
          tabindex="-1"
          aria-hidden="true"
        />
      </div>
      <div style="text-align: center">
        <input button type="submit" name="search" value="search" />
      </div>
    </form>

      <table id="flashmsg">
        {% if results %}
        {% for result in results %}
        <form method="post">
           {% if result.get("google_product_id", None) %}
            <input type="hidden" name="google_product_id" value="{{ result.pop('google_product_id') }}" />
           {% endif %}
          <tr rowspan="2">
          {% for key, value in result.items() %}
            {% if key=="img" %}
            <td>
                  <input type="hidden" name="{{ key }}" value="{{ value }}" />
                  <img
                    src="{{ value }}"
                    style="width: 110px; height: 110px"
                  />
            </td>
            {% elif key=="url" %}
            <td>
                  <input type="hidden" name="{{ key }}" value="{{ value }}" />
                  <a href="{{ value }}" />Buy Now</a>
            </td>
            {% else %}
            <td>
              <input type="hidden" name="{{ key }}" value="{{ value }}" />{{ value }}
            </td>

            {% endif %}

          {% endfor %}
            <td>
              <input
                    type="number"
                    name="dprice"
                    placeholder="Enter desired price:"
                    required
              />Enter the desired price to track.
            </td>
            <td>
                <button type="submit" name="traceprice" onclick="{{ window }}">
                  Track Price
                </button>
            </td>
          </tr>
        </form>
        {% endfor %}
        {% endif %}
      </table>
  </body>
</html>

templates/website/newpass.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='website/index.css') }}">
  </head>
  <body>
      <div class="hea">
        <div class="logo">
<h1><span>P</span>RICE   <span style="padding-left:10px;">T</span>AG</h1>
        </div>
        <div class="menu">
          <a href="#" style="display:none;">About Us</a>
          <a href="#" style="display:none;">Sites</a>
        </div>
      </div>

      <form class="npass" action="{{ url_for('user.newpass') }}" method="post">
          <span>
              {% with msg = get_flashed_messages() %}
              {% if msg %}
                    {{ msg }}
              {% endif %}
              {% endwith %}

          </span>
        <span style="text-decoration:underline;">Enter Code sent to email:</span><br><br>
        <input type="text" name="code" placeholder="Enter code:"><br>
        <input type="password" name="pas" placeholder="New Password:"><br>
        <input type="password" name="cpas" placeholder="Confirm Password:"><br>
        <br><br><button type="submit" name="button" >Change Password</button>
      </form>
  </body>
</html>

templates/website/notifications.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <title>Home</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static',filename='website/index.css') }}"
    />

    <link
      href="https://fonts.googleapis.com/css?family=Tomorrow&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300&display=swap"
      rel="stylesheet"
    />
    <style> 
      h1 {
        text-align: center;
      }

      /* .holder {
        display: flex;
        align-items: center; 
        justify-content: center;
      }  */

      /* .row {
        background: white;
        border-radius: 5px;
        padding: 5px;
        font-size: 20px;
        height: 30px;
        display:flex;
        align-items:center;
      } */

      .row a{
        text-decoration: none;

      }
    </style>
  </head>
  <body class="home">
    <header>
      <div class="hea">
        <div class="logo">
          <h1>
            <span>P</span>RICE <span style="padding-left: 10px">T</span>AG
          </h1>
        </div>

        <div class="menu">
          <a href="#" style="display: none">About Us</a>
          <a href="#" style="display: none">Sites</a>
          <a href="{{ url_for('user.login') }}">Log Out</a>
          <a href="{{ url_for('user.profile')}}">Profile</a>
          <a href="{{ url_for('views.dashboard', token=token) }}">Dashboard</a>
          <a href="{{ url_for('views.home')}}" class="hom">Home</a>
          <a href="{{ url_for('notifications.notification')}}">Notifications</a>
        </div>
      </div>
    </header>
    <!-- welcome,{{email}} -->
      <h1>Notifications</h1>
        <div class="holder">
        {% for notification in notifications %}
        {% if not notification.is_read %}
        <div class="row">
          <table>
            <td>
              <img src="{{ notification.product.img }}" style="height:50px;width:50px;">
            </td>
            <td>
              <a style="margin-left: 5px ; width:80px;" href="{{ url_for('views.dashboard') }}">
                {{ notification.message }}
              </a>
            </td>
            <td> 
              <a style="height:50px;width:50px;" href="{{ url_for('notifications.mark_read', notification_id=notification['id'] ) }}">Mark as read</a>
            </td>
          </table>
        </div>
        {% endif %}
        {% endfor %}
        </div>
  </body>
</html>

templates/website/profile.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Profile</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='website/index.css') }}">



  </head>
  <body class="profilebody">
      <div class="hea">
        <div class="logo">
<h1><span>P</span>RICE   <span style="padding-left:10px;">T</span>AG</h1>        </div>

        <div class="menu">
          <a href="#" style="display:none;">About Us</a>
          <a href="#" style="display:none;">Sites</a>
            <a href="{{ url_for('user.login') }}" >Log Out</a>
          <a href="{{ url_for('user.profile')}}" class="pro">Profile</a>
          <a href="{{ url_for('views.dashboard') }}">Dashboard</a>
          <a href="{{ url_for('views.home')}}">Home</a>
                      <a href="{{ url_for('notifications.notification')}}">Notifications</a>

        </div>
      </div>


      <form class="profile" method="post">
        <span>Name:</span> <br><input type="text" name="name" placeholder="Enter name:" id="name" value="{{ user }}" disabled><br><br>
        <span>Username:</span> <br><input type="text" name="user" placeholder="Enter email id:" id="user" value="{{ email }}" disabled><br><br>
        <span>Mobile No:</span> <br><input type="tel" name="mob" placeholder="Enter Mobile:" id="mob" value="{{ mob }}" disabled><br><br>
        <button type="button" name="edit" id="edit" onClick="document.getElementById('name').disabled = false;
        document.getElementById('user').disabled = false;
        document.getElementById('mob').disabled = false;
        document.getElementById('confirm').style.display = 'block';
        document.getElementById('edit').style.display = 'none';">Edit Profile</button>
        <button type="submit" name="confirm" id="confirm" style="display:none;margin-left:135px;">Confirm</button>
        <br><br>
        <a href="{{ url_for('user.forgetpass') }}">Change Password</a>
      </form>

  </body>
</html>

templates/website/signup.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Signup</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='website/index.css') }}">
  </head>
  <body class="signupbody">
      <div class="hea">
        <div class="logo">
<h1><span>P</span>RICE   <span style="padding-left:10px;">T</span>AG</h1>        </div>

        <div class="menu">
          <a href="#" style="display:none;">About Us</a>
          <a href="#" style="display:none;">Sites</a>
        </div>
      </div>


      <form class="sign" method="post">

          {% with msg = get_flashed_messages() %}
            {% if msg %}
                {% for i in msg %}
                    <p style="color:red;text-decoration:underline;">{{ i }}</p>
                {% endfor %}
          {% endif %}
          {% endwith %}

        <span>Name:</span> <br><input type="text" name="name" placeholder="Enter name:"><br><br>
        <span>Username:</span> <br><input type="text" name="user" placeholder="Enter email id:"><br><br>
        <span>Password:</span> <br><input type="password" name="pas" placeholder="Enter password:"><br><br>
        <span>Confirm Password:</span> <br><input type="password" name="cpas" placeholder="Confirm password:" >

          <br>
        <span>Mobile No:</span> <br><input type="tel" name="mob" placeholder="Enter Mobile:"><br><br>
        <button type="submit" name="signin">SIGN IN</button><br><br><br>
        <a href="{{ url_for('user.login')}}">Already have an account? Please Log in</a>



      </form>


  </body>
</html>

templates/website/sites.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>sites</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='website/index.css') }}">

</head>
<body>

    <header>
      <div class="hea">
        <div class="logo">
<h1><span>P</span>RICE   <span style="padding-left:10px;">T</span>AG</h1>        </div>

        <div class="menu">
          <a href="#" style="display:none;">About Us</a>
          <a href="#" style="display:none;">Sites</a>
          <a href="{{ url_for('profile')}}">Profile</a>
          <a href="#">Dashboard</a>
          <a href="{{ url_for('home')}}" class="hom">Home</a>
        </div>
      </div>
    </header>




</body>
</html>

templates/website/track_price.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Track_Price</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='website/index.css') }}">

    <link href="https://fonts.googleapis.com/css?family=Tomorrow&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300&display=swap" rel="stylesheet">
  </head>
  <body class="home">
    <header>
      <div class="hea">
        <div class="logo">
<h1><span>P</span>RICE   <span style="padding-left:10px;">T</span>AG</h1>        </div>

        <div class="menu">
          <a href="#" style="display:none;">About Us</a>
          <a href="#" style="display:none;">Sites</a>
          <a href="{{ url_for('profile')}}">Profile</a>
          <a href="#">Dashboard</a>
          <a href="{{ url_for('home')}}" class="hom">Home</a>
        </div>
      </div>
    </header>



<table id="flashmsg">
    <tr rowspan=2>
  {% with msg = get_flashed_messages() %}
            {% if msg %}
                {% for i in range(5) %}
                    {% if i == 1 %}
                     <td name="{{ msg[i] }}"><input type="hidden" name = "{{msg[i]}}" value="{{ msg[i] }}"/><img src='{{ msg[i] }}' style='width:110px;height:110px;'/></td>
                    {% else %}
                    <td name="{{ msg[i] }}"><input type="hidden" name="{{msg[i]}}" value="{{ msg[i] }}"/>{{msg[i]}}</td>
                    {% endif %}
                {% endfor %}
          {% endif %}
          {% endwith %}
    </tr>
</table>


  </body>
</html>